version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=notes-app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
